### ISSUE TITLE
Failed to reading data from non-liquid sensor

### ISSUE THREAD

**Issue by IMAN4K** [Jacajack/avr-ds18b20#1]
Hi and thanks for `avr-ds18b20`.

I'm trying to read temp from a non-liquid `DS18B20` sensor (+ `4.7K` pull-up resistor) using an `ATmega8A`.
The simple routine looks like this:
```
#include <avr/io.h>
#include <stdio.h>

#define F_CPU 11059200
#include <util/delay.h>

#define D4 eS_PORTB0
#define D5 eS_PORTB1
#define D6 eS_PORTB2
#define D7 eS_PORTB3
#define RS eS_PORTB5
#define EN eS_PORTB4
#include "lcd.h"

#include "ds18b20/ds18b20.h"

int main() {
	DDRB = 0xFF;
	Lcd4_Init();

	char buff[16];
	int temperature;
	uint8_t code1, code2;

	while (1) {
		code1 = ds18b20convert(&PORTC, &DDRC, &PINC, (1 << PORTC0), NULL);
		_delay_ms(1000);
		code2 = ds18b20read(&PORTC, &DDRC, &PINC, (1 << PORTC0), NULL, &temperature);

		sprintf(buff, "%d %d %d", code1, code2, temperature);
		Lcd4_Clear();
		Lcd4_Write_String(buff);
	}
	return 0;
}
```
But the reading and converting procedures both will fail with error code `DS18B20_ERROR_COMM`.
I'm 100% sure of the sensor (already tested with Arduino) and the circuitry.
What might be the problem here ?

Regards.

**Comment by Jacajack** [comment]
Hi,

`DS18B20_ERROR_COMM`  means that at some point `onewireInit` routine has failed. This can be due to improper timings inside the function. In your code I can't see any obvious errors, but I noticed you are using some atypical `F_CPU` value. I have never tested the library with such settings, but it's mainly based on `_delay` calls from `util/delay.h` which shouldn't have any problem with preserving equal time periods unless CPU frequency is badly defined.

That leads me to ask you if you are sure you've built `avr-ds18b20` library with the exact same `F_CPU` setting? If not, that can be the source of all problems. Please always be cautious about that (even if it's not the case here), because you won't get any warning about macro values mismatch in two independent code modules.

For your case, the make call should look like that `make F_CPU=11059200UL MCU=atmega8`. If you are using your own makefile, you can add recursive `make` invocation in there as follows:
```makefile
all:
  make -C avr-ds18b20 F_CPU=11059200UL MCU=atmega8
  ...

clean:
  make -C avr-ds18b20 clean
  ...

```
Where `avr-ds18b20` is relative path to the library directory.

Obviously, that's just guessing, but please try rebuilding the library (just to be sure) and see if it helps.
I hope this resolves your issue :)

**Comment by IMAN4K** [comment]
Yeah thanks.
That was the frequency mismatch!

**Comment by Jacajack** [comment]
I'm glad I could help :)
