### ISSUE TITLE
interrupts

### ISSUE THREAD

**Issue by drdbrr** [Jacajack/avr-ds18b20#2]
Hi, I am using you ds18b20 library in my modbus project on atmega328. I wants to inform you about little issue, yaMBSiavr modbus library doesn't work until I comment all cli() interrupt disable functions. I know this functions needed for proper readings of sensor. But without cli() sensor works fine with multiple other connected sensors like dht22, mq135 on the same board.

**Comment by Jacajack** [comment]
Hi,

The occurrence of the problem you are describing may strongly depend on the interrupt frequency of the yaMBSiavr Modbus library and the frequency of calling the `avr-ds18b20` library functions. So far I haven't faced such an issue before, but I do realize that explicit `cli()` omitting should be possible to configure during compilation, because it might be useful in cases like yours.

I'll add this feature soon, so please stay tuned to updates :)

Thank you for reporting this issue
